# Site settings
title: Introducción a UNIX - 2017
email: rdanielmillan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Electiva N° 182 Introducción a UNIX
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# baseurl: /R-2017

# Build settings
markdown: kramdown
show_drafts: FALSE
plugins_dir: _plugins
exclude: ["gulp", '*.org', '*feed*', 'Gemfile*']

# theme: jekyll-theme-minimal
